### ISSUE TITLE
Add customization to scrolling from bottom to top

### ISSUE THREAD

**Issue by fichna** [saurabharora90/InfiniteRecyclerView#2]
Hi, this is awesome lib, but what I must to do when I want to "rotate" this process? When I want to use this library for app like chat where the newest messages are at the bottom and infinite scroll behavior would be from bottom to top?
Thanks for reply!

**Comment by fichna** [comment]
Oh, my fault... 

```
mLayoutManager.setReverseLayout(true);
mLayoutManager.setStackFromEnd(true);
```
isn't it?

**Comment by saurabharora90** [comment]
Hi @fichna 

My rough guess is that it should work but I haven't tried it out. Did you give it a shot? Let me know how it went; if it didn't work, I can look into adding support for it :)

**Comment by fichna** [comment]
It's working :+1:
